# NumPy Array Operations

In [1]:
import numpy as np

## Slicing
- Slicing in NumPy allows you to extract a portion of an array by specifying a range of indices

- array[start:stop:step]

In [10]:
# 1-D Array

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[:4])
print(arr[1:6:2])
print(arr[::-1]) # Reverse an array

[10 20 30 40]
[20 40 60]
[60 50 40 30 20 10]


In [21]:
# 2-D Array

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Specific element: ", arr[2, 0])
# First -> row, Second -> Column
print("Entire row: ", arr[1])
print("Enitre column: ", arr[:, 1])

# Row 1 to end, Column 0 and 1
print(arr[1:, :2]) 

Specific element:  7
Entire row:  [4 5 6]
Enitre column:  [2 5 8]
[[4 5]
 [7 8]]
