# NumPy
NumPy stands for "Numerical Python" and it provides efficient, multi-dimensional array objects and a large collection of mathematical functions to operate on these arrays.

In [2]:
# This is how we import NumPy library and it is commonly imported with the alias 'np'

import numpy as np

# Creating Array from the list

In [3]:
arr_1d = np.array([1, 2, 3])
print("1-D Array\n", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2-D Array\n", arr_2d)

# This is how we create 1-dimensional and 2-dimensional array.

1-D Array
 [1 2 3]

2-D Array
 [[1 2 3]
 [4 5 6]]


### Array of Zeros

In [4]:
zeros = np.zeros((3, 4)) # 3 * 4 matrix of all zeros
print("Zero matrix\n", zeros)

Zero matrix
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Array Of Ones

In [5]:
ones = np.ones((3, 4)) # 3 * 4 matrix of all ones
print("One matrix\n", ones)

One matrix
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Difference between Python List and NumPy Array

In [6]:
python_list = [1, 2, 3, 4]  # Doubles the list
print("Python list multiplication:\n", python_list * 2)

numpy_arr = np.array([1, 2, 3, 4]) # Element wise multiplication
print("\nNumPy array multiplication:\n", numpy_arr * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nTime taken by python list: ", time.time() - start)

np_arr = np.arange(1000000) * 2
print("\nTime taken by NumPy array: ", time.time() - start)

Python list multiplication:
 [1, 2, 3, 4, 1, 2, 3, 4]

NumPy array multiplication:
 [2 4 6 8]

Time taken by python list:  0.03291511535644531

Time taken by NumPy array:  0.035629987716674805


### Array filled with a specific value

In [7]:
full_arr = np.full((3, 3), 10)
print("Full array is:\n", full_arr)

# This will print the 3*3 matrix with value 10.

Full array is:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


### Empty arrays (uninitialized)

In [8]:
empty_arr = np.empty((2, 3))
print("Empty array:\n", empty_arr)

Empty array:
 [[0. 0. 0.]
 [0. 0. 0.]]


### Random module

In [9]:
random = np.random.random((2, 3))
print("Radnom array:\n", random)

# This will generate matrix with random values fluctuating between 0 and 1.

Radnom array:
 [[0.21268417 0.93418568 0.16561844]
 [0.08794129 0.08531035 0.00129735]]


### Sequence Array

In [10]:
sequence_arr = np.arange(0, 10, 2)
print("Sequence array:\n", sequence_arr)

Sequence array:
 [0 2 4 6 8]


## Vector
- A vector is a one-dimensional array of numbers that has both magnitude and direction.
- Geometrically, a vector represents a point or a direction in space.
- It can be thought of as a list of numbers, such as $$$$.
- In NumPy, vectors are 1D arrays.
Example:

In [11]:
vector = np.array([3, 5, 7])
print("Vector:\n", vector)

Vector:
 [3 5 7]


## Matrix
- A matrix is a two-dimensional array of numbers arranged in rows and columns.
- It can be viewed as a collection of vectors or an operator acting on vectors.
- Matrices are used for transformations, systems of linear equations, and tabular data.
- In NumPy, matrices are 2D arrays.
Example:

In [12]:
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2]
 [3 4]]


## Tensor
- A tensor is a generalization of vectors and matrices to potentially higher dimensions.
- Technically, tensors are multi-dimensional arrays (3D, 4D, and beyond).
- Scalars (single numbers) are 0D tensors, vectors 1D tensors, and matrices 2D tensors.
- Tensors represent more complex data like colored images (3D), video data (4D), or higher dimensional datasets.
Example (3D tensor):

In [13]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# NumPy Array Properties

In [14]:
arr = np.array([[1, 2, 3],[4, 4, 6]])

print("Array:\n", arr, "\n")
print("Shape: ", arr.shape,"\n")  # Order of the array
print("Dimension: ", arr.ndim,"\n") # Dimension of the array
print("Size: ", arr.size,"\n") # Number of elements
print("Data Type: ", arr.dtype)

Array:
 [[1 2 3]
 [4 4 6]] 

Shape:  (2, 3) 

Dimension:  2 

Size:  6 

Data Type:  int64


### Array Reshaping

In [15]:
# np.reshape() changes the shape of an array without changing its data.
arr = np.arange(6)
print("Original array:\n", arr, "\n")

reshaped_arr = arr.reshape((2, 3))
print("Reshaped array:\n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()
print("\nFlattened array:\n", flattened_arr)

# ravel returns original array, instead of copy
raveled_arr = reshaped_arr.ravel()
print("\nRaveled array:\n", raveled_arr)

Original array:
 [0 1 2 3 4 5] 

Reshaped array:
 [[0 1 2]
 [3 4 5]]

Flattened array:
 [0 1 2 3 4 5]

Raveled array:
 [0 1 2 3 4 5]


## Manipulation Methods

In [16]:
x = np.array([4, 5, 6])
print("Origianl array:\n", x)

# x[2] = 3. -> Replace value at index 2

# np.append() -> Append values at the end
new_x = np.append(x, [10])
print("\nAppended array:\n", new_x)

# np.delete() -> Delete elements from an array.
del_x = np.delete(x, 1)
print("\nDeleted array:\n", del_x)

# np.insert() -> Insert value at a given index
ins_x = np.insert(x, 0, 3)
print("\nInserted array:\n", ins_x)

# np.concatenate() -> Join two or more arrays
y = np.array([1, 2, 3])
concatenated_arr = np.concatenate((y, x))
print("\nConcatenated array:\n", concatenated_arr)

# np.transpose() or .T Swaps axes to get the transpose of a matrix
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transpose_arr = arr.T
print("\n Original matrix:\n", arr)
print("\n Transposed matrix:\n", transpose_arr)


Origianl array:
 [4 5 6]

Appended array:
 [ 4  5  6 10]

Deleted array:
 [4 6]

Inserted array:
 [3 4 5 6]

Concatenated array:
 [1 2 3 4 5 6]

 Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Transposed matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Mathematical Operations
- Element-wise operations like addition, subtraction, multiplication, power:

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("\nAddition: ", arr1+arr2)
print("\nSubtraction: ", arr1 - arr2)
print("\nMultiplication: ", arr1*arr2)
print("\nSquare: ", np.power(arr1, 2))
print("\nSquare Root: ", np.sqrt(arr2))


Addition:  [5 7 9]

Subtraction:  [-3 -3 -3]

Multiplication:  [ 4 10 18]

Square:  [1 4 9]

Square Root:  [2.         2.23606798 2.44948974]


## Statistical Methods
- Calculate mean, median, standard deviation:

In [18]:
arr = np.array([1, 2, 2, 3, 4])
print("\nMean: ", np.mean(arr))
print("\nMedian: ", np.median(arr))
print("\nStandard Deviation: ", np.std(arr))


Mean:  2.4

Median:  2.0

Standard Deviation:  1.019803902718557


## Sorting
- np.sort() sorts element in an array.

In [19]:
# 1-D Array

arr = np.array([5, 4, 3, 2, 1])
sorted_arr = np.sort(arr)
print("Original array: ", arr)
print("\nSorted array: ", sorted_arr)

Original array:  [5 4 3 2 1]

Sorted array:  [1 2 3 4 5]


In [22]:
# 2-D Array
arr_2d = np.array([[3, 1], [1, 2], [3, 2]])
print("Original 2-D array:\n", arr_2d, "\n")
print("Sorted 2-D array by column:\n", np.sort(arr_2d, axis=0), "\n")
print("Sorted 2-D array by row:\n", np.sort(arr_2d, axis=1))

Original 2-D array:
 [[3 1]
 [1 2]
 [3 2]] 

Sorted 2-D array by column:
 [[1 1]
 [3 2]
 [3 2]] 

Sorted 2-D array by row:
 [[1 3]
 [1 2]
 [2 3]]


## Indexing for Max/Min
- np.argmax() and np.argmin(): Get the index of the maximum or minimum value.

In [21]:
arr = np.array([3, 1, 4, 2])
print("Index of maximum value: ", np.argmax(arr))
print("\nIndex of minimum value: ", np.argmin(arr))

Index of maximum value:  2

Index of minimum value:  1
