# NumPy Array Operations

In [1]:
import numpy as np

### Understanding Axes in NumPy Arrays
- Axis 0 refers to the rows (down the rows, vertically).
- Axis 1 refers to the columns (across the columns, horizontally).
- For higher dimensions, axes continue to extend: axis 2, axis 3, etc.

In [5]:
# Applying Functions Along Axes
# Example Array

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)

(2, 3)


In [16]:
# Sum of all elements
total_sum = np.sum(arr)
print("Total sum:", total_sum, "\n")

# Sum along rows (axis = 1) (sum across each row)
sum_rows = np.sum(arr, axis = 1)
print("Sum across rows:", sum_rows, "\n")

# Sum along columns (axis = 0) (sum across each column)
sum_cols = np.sum(arr, axis = 0)
print("Sum acorss columns:", sum_cols, "\n")

# Mean along columns:
mean_cols = np.mean(arr, axis = 0)
print("Mean along columns:", mean_cols, "\n")

# Mean along rows:
mean_rows = np.mean(arr, axis = 1)
print("Mean along rows:", mean_rows, "\n")

# Max and Min along the rows
max_rows = np.max(arr, axis = 1)
print("Maximum value along rows:", max_rows, "\n")

min_rows = np.min(arr, axis = 1)
print("Minimum value along rows:", min_rows)

Total sum: 21 

Sum across rows: [ 6 15] 

Sum acorss columns: [5 7 9] 

Mean along columns: [2.5 3.5 4.5] 

Mean along rows: [2. 5.] 

Maximum value along rows: [3 6] 

Minimum value along rows: [1 4]


### Chainging number of dimensions of an array:
In NumPy, changing the number of dimensions of an array is often necessary, especially when preparing data for certain computations or machine learning models. Two important functions for this are np.expand_dims() and np.squeeze().

- np.expand_dims()
  - Adds a new dimension (axis) to an array at a specified position.
  - Useful to increase the dimensionality of an array, for instance, converting a 1D array into a 2D array.

Syntax:
```
np.expand_dims(array, axis)
```
- axis: Position where the new dimension is added.

In [ ]:
arr = np.array([1, 2, 3])
print("Original arrray:\n",arr)
print("Original shape", arr.shape, "\n")

# Here, we added a new dimension at axis 0 (the front).
# Now the array is 2D with 1 row and 3 columns.
expanded_arr = np.expand_dims(arr, axis = 0)
print("Expanded array:\n", expanded_arr)
print("Expanded array shape:", expanded_arr.shape, "\n")


# Here, we added a new dimension at axis 1 (the second axis).
# Now the array is 2D with 3 rows and 1 column.
expanded_arr2 = np.expand_dims(arr, axis = 1)
print("Expanded array:\n", expanded_arr2)
print("Expanded array shape:", expanded_arr2.shape)

Original arrray:
 [1 2 3]
Original shape (3,) 

Expanded array:
 [[1 2 3]]
Expanded array shape: (1, 3) 

Expanded array:
 [[1]
 [2]
 [3]]
Expanded array shape: (3, 1)
