# NumPy Array Operations

In [1]:
import numpy as np

## Slicing
- Slicing in NumPy allows you to extract a portion of an array by specifying a range of indices

- array[start:stop:step]

In [2]:
# 1-D Array

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[:4])
print(arr[1:6:2])
print(arr[::-1]) # Reverse an array

[10 20 30 40]
[20 40 60]
[60 50 40 30 20 10]


In [4]:
# 2-D Array

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Specific element: ", arr[2, 0])
# First -> row, Second -> Column
print("Entire row: ", arr[1])
print("Enitre column: ", arr[:, 1])

# Row 1 to end, Column 0 and 1
print(arr[1:, :2]) 

# All rows and 2nd column
print(arr[:, 2])

Specific element:  7
Entire row:  [4 5 6]
Enitre column:  [2 5 8]
[[4 5]
 [7 8]]
[3 6 9]


## Filter
- NumPy filter operations allow selecting elements from an array that meet specific conditions, most commonly using Boolean indexing (Boolean mask arrays). This technique is efficient, concise, and widely used in data analysis.

### Filtering Even or Odd Elements

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
even = arr[arr % 2 == 0]
odd = arr[arr % 2 != 0]
print(f"Even: {even}")
print(f"Odd: {odd}")

# Any condition can be used to filter elements for quick selection.

Even: [2 4 6]
Odd: [1 3 5]


### Filter with mask

In [26]:
mask = arr % 2 == 0
print("Even numbers are:", arr[mask])

arr = np.array([41, 42, 43, 44])
mask = arr > 41
print("Numbers greater than 41 are:", arr[mask])

Even numbers are: [42 44]
Numbers greater than 41 are: [42 43 44]


### Multiple Conditions (AND, OR, NOT)

In [21]:
arr = np.array([1, 5, 10, 15, 18, 27, 16, 19])
# Select numbers between 5 and 15
filtered = arr[(arr > 5) & (arr < 20)]
print(f"Numbers between 5 and 15: {filtered}")

filtered_or = arr[(arr < 5) | (arr > 15)]
print(filtered_or)

# Logical operators enable complex filtering criteria

Numbers between 5 and 15: [10 15 18 16 19]
[ 1 18 27 16 19]


### Using np.where()

In [23]:
arr = np.array([1, 5, 8, 10, 12, 18, 20])
indices = np.where(arr > 10)
print(indices)

filtered = arr[indices]
print(filtered)

# np.where() gives indices of matching elements, which can be used for further selection

(array([4, 5, 6]),)
[12 18 20]


## Fancy Indexing
- Fancy indexing allows selecting specific elements from an array using a list or array of integer indices (positions).
- It can be used to quickly grab non-contiguous elements, rows, or columns, and is especially useful for advanced data selection.
- It creates a new array containing the elements at the positions specified.
- It can also work with multi-dimensional arrays for selecting specific rows, columns, or elements

## np.where()
- np.where() is a function that returns the indices where a condition is True.
- It works with Boolean conditions and is commonly used in filtering. It can be used to directly select the elements (like a filter) or to get the indices for further processing.
- It offers more flexibility by allowing both filtering and replacement in one step.

In [31]:
# Fancy Indexing

arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
selected = arr[indices]
print("Selected values are:", selected)

# np.where()

indices2 = np.where(arr > 20)
print("Selected using np.where() are:", arr[indices2])

# You can also use np.where() for conditional assignment, See below the explanation

Selected values are: [10 30 50]
Selected using np.where() are: [30 40 50]


- np.where() is a powerful function in NumPy used for conditional selection, filtering, and assignment within arrays. It is versatile and widely used in array manipulation and data analysis.

In [34]:
arr = np.array([10, 20, 30, 40, 50, 60])
indices = np.where(arr > 20)
print(arr[indices])

# Conditional replacement
replace_with_zero = np.where(arr > 25, arr, 0)
print("Conditional replacement:", replace_with_zero)

[30 40 50 60]
Conditional replacement: [ 0  0 30 40 50 60]


- np.where(condition[, x, y])

### What np.where(condition, x, y) does
- It’s like a vectorized if-else for arrays:
- For every element in arr:
  - `If condition is True → pick value from x`
  - `Else → pick value from y`
- So the general formula is:
  - np.where(condition, value_if_true, value_if_false)

In [38]:
# Example
nums = np.arange(1, 11)

conditional_arr = np.where(nums > 5, nums*5, nums)
print("Conditional array is:", conditional_arr)

Conditional array is: [ 1  2  3  4  5 30 35 40 45 50]


In [40]:
# Applying np.where() in 2d array.
arr_2d = np.array([[1, 10], [2, 20]])
result = np.where(arr_2d > 5, arr_2d, -1)
print("Result of np.where() on a 2d array:\n", result)

Result of np.where() on a 2d array:
 [[-1 10]
 [-1 20]]


## Broadcasting
- NumPy handles mathematical operations on arrays of different sizes using a feature called broadcasting. Broadcasting is a set of rules that automatically expands smaller arrays to match the shape of larger ones, so element-wise operations can be performed efficiently.

### How Broadcasting Works
- If arrays have the same shape, operations are performed element-wise.
- If shapes are different, NumPy tries to “stretch” (broadcast) the smaller array along the missing or mismatched dimensions, without copying data.
- For broadcasting to work:
  - The dimensions must be equal, or
  - One of them must be 1 for that dimension

In [52]:
### 1. Array and Scalar (Simplest)
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = arr + 10

print("Addition of scalar into array:\n", result, "\n")

# Each element of the array is increased by 10. The scalar value automatically broadcasts to all elements.

### 2. 1D and 2D Arrays
arr_1d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d = np.array([10, 20, 30])
result2 = arr_1d + arr_2d

print("Addition of 1-d and 2-d array:\n", result2, "\n")

# The 1D array "expands" to match each row of the 2D array

### 3. Example: 1D and Column Vector
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
result3 = a + b
print("Addition of 1-d array and column vector:\n", result3)

# The 1D array a is broadcasted across each row in the 2D array b

Addition of scalar into array:
 [[11 12 13]
 [14 15 16]] 

Addition of 1-d and 2-d array:
 [[11 22 33]
 [14 25 36]] 

Addition of 1-d array and column vector:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


### Broadcasting Rules
- Start from trailing axis (last dimension), compare dimensions.
- If they are equal, or one of them is 1, they're compatible.
- Otherwise, broadcasting fails and the operation won't work.
- NumPy creates a virtual expanded array rather than copying data, making operations efficient.

### Key Takeaways
- Broadcasting makes NumPy vectorized operations intuitive and fast.
- When shapes are compatible, mathematical operations like addition, subtraction, multiplication, and division just work without explicit looping or reshaping.
- If shapes are incompatible, a ValueError is raised.
- In practice, always check array shapes and rely on broadcasting for efficient, concise array math

- Before performing mathematical operations on NumPy arrays, always check their shapes. Broadcasting lets differently shaped arrays interact, but only if their shapes are compatible. This ensures fast, loop-free, and memory-efficient calculations.

### Why Check Array Shapes?
- Shape Compatibility: Only specific shape combinations support broadcasting. Incompatible shapes cause errors.
- Predictable Results: Knowing shapes helps predict how arrays will combine—across rows, columns, or higher dimensions.
- Error Prevention: Broadcasting errors (ValueError) are common if shapes aren't checked.

### How to Check Shapes
Use the .shape attribute for any NumPy array: See example below ->

In [66]:
a = np.array([[10, 20, 30], [40, 50, 60]])
b = np.array([1, 2, 3])

print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

# Compare shapes before operations to see if they are compatible for broadcasting.

## Broadcasting in Practice
# Example 1: Compatible Shapes

# Shapes: (2, 3) + (3,) → OK (broadcast across rows)

result = a + b
print("Addition of a and b:\n", result)

# Broadcasting stretches b to each row of a.

# Example 2: Incompatible Shapes
c = np.array([1, 2])
# Shapes: (2, 3) + (2,)    → Not compatible
# result2 = a + c
# print("Addition of a and c:\n", result2)
# Raises: ValueError: operands could not be broadcast together with shapes (2,3) (2,)

Shape of a: (2, 3)
Shape of b: (3,)
Addition of a and b:
 [[11 22 33]
 [41 52 63]]


- Different trailing dimensions and no dimension is 1, so operation fails.

### Best Practices for Efficient Array Math
- Check .shape for all arrays before operations, especially in complex calculations or pipelines.
- Trust NumPy broadcasting for most element-wise ops—it's faster and requires less code than Python loops.
- Use broadcasting for scaling, shifting, combining data batch-wise, or applying functions along specific axes.

Properly using broadcasting leads to cleaner, faster, and less error-prone code in scientific computations and data analysis.

In NumPy broadcasting, compatibility between shapes is determined by comparing dimensions from right (trailing) to left according to these rules:
1. Dimensions are compatible if they are equal.
2. Dimensions are compatible if either dimension is 1.
3. Otherwise, they are not compatible.

### Example 1: Shapes (2, 3) + (3,)
- Compare rightmost dimensions:
  - 3 vs 3 → equal, compatible.
- Next dimension:
  - 2 vs none (since (3,) has only 1 dimension, treat missing leading dimension as 1)
  - 2 vs 1 → compatible since 1 can be broadcast.
  
  > When comparing the shapes of two arrays for broadcasting, NumPy compares dimensions starting from the right (the last dimension) and moves leftwards.
  >
  > If one array has fewer dimensions (like a 1D array with shape (3,)) and the other has more dimensions (like a 2D array with shape (2, 3)), NumPy pretends the smaller array has extra dimensions of size 1 on the left to match the number of dimensions.
  >
  > So, the array with shape (3,) is treated as if it were (1, 3) for the sake of comparison.
  > 
  > Now, when comparing:
  > - The last dimension: 3 (from both arrays) → they match.
  > - The next dimension: 2 (from the bigger array) vs. 1 (pretend extra dimension on the smaller array) → compatible because size 1 means this dimension can be "stretched" to 2.

- So shapes (2, 3) and (3,) are compatible.
- Here the (3,) array is broadcast across rows of (2, 3).

### Example 2: Shapes (2, 3) + (2,)
- Compare trailing dimensions:
  - 3 vs 2 → Not equal and neither is 1 → incompatible.
- So shapes (2, 3) and (2,) are not compatible.
- Broadcasting fails in this case.

### np.vstack()
- Stands for vertical stack.
- Used to stack arrays vertically (row-wise), i.e., adds arrays as new rows.
- Arrays to be stacked must have the same number of columns (same width).
- Returns a new array with the input arrays stacked one on top of another.

In [68]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
result = np.vstack((a, b))
print("V-stack:\n", result)

V-stack:
 [[1 2]
 [3 4]
 [5 6]]


### np.hstack()
- Stands for horizontal stack.
- Used to stack arrays horizontally (column-wise), i.e., adds arrays as new columns.
- Arrays must have the same number of rows (same height).
- Returns a new array with the input arrays stacked side-by-side.

In [69]:
a = np.array([[2, 3], [4, 5]])
b = np.array([[1], [2]])
result = np.hstack((a, b))
print("H-stack:\n", result)

H-stack:
 [[2 3 1]
 [4 5 2]]


### np.delete()
- np.delete() removes elements along a specified axis.
- Syntax: np.delete(arr, obj, axis=None)
  - arr: input array.
  - obj: index or slice or array of indices to delete.
  - axis: dimension along which to delete (optional, default None).
- Returns a new array with the specified elements removed.

In [70]:
# Examples:
# Delete element at index 1 in a 1D array:
a = np.array([1, 2, 3, 4, 5])
result = np.delete(arr, 1)
print("Modified array:", result)

Modified array: [1 3 4 5 6]


In [87]:
# Delete row at index 0 in a 2D array:
b = np.array([[1, 2], [3, 4], [5, 6]])
new_b = np.delete(b, 0, axis=0)
print("Modified new array:\n", new_b)

Modified new array:
 [[3 4]
 [5 6]]


In [88]:
# Delete column at index 1 in a 2D array:
c = np.array([[1, 2], [3, 4], [5, 6]])
new_c = np.delete(c, 1, axis=1)
print("Modified new array:\n", new_c)

Modified new array:
 [[1]
 [3]
 [5]]
