# NumPy Array Operations

In [2]:
import numpy as np

### Understanding Axes in NumPy Arrays
- Axis 0 refers to the rows (down the rows, vertically).
- Axis 1 refers to the columns (across the columns, horizontally).
- For higher dimensions, axes continue to extend: axis 2, axis 3, etc.

In [3]:
# Applying Functions Along Axes
# Example Array

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)

(2, 3)


In [4]:
# Sum of all elements
total_sum = np.sum(arr)
print("Total sum:", total_sum, "\n")

# Sum along rows (axis = 1) (sum across each row)
sum_rows = np.sum(arr, axis = 1)
print("Sum across rows:", sum_rows, "\n")

# Sum along columns (axis = 0) (sum across each column)
sum_cols = np.sum(arr, axis = 0)
print("Sum acorss columns:", sum_cols, "\n")

# Mean along columns:
mean_cols = np.mean(arr, axis = 0)
print("Mean along columns:", mean_cols, "\n")

# Mean along rows:
mean_rows = np.mean(arr, axis = 1)
print("Mean along rows:", mean_rows, "\n")

# Max and Min along the rows
max_rows = np.max(arr, axis = 1)
print("Maximum value along rows:", max_rows, "\n")

min_rows = np.min(arr, axis = 1)
print("Minimum value along rows:", min_rows)

Total sum: 21 

Sum across rows: [ 6 15] 

Sum acorss columns: [5 7 9] 

Mean along columns: [2.5 3.5 4.5] 

Mean along rows: [2. 5.] 

Maximum value along rows: [3 6] 

Minimum value along rows: [1 4]


### Chainging number of dimensions of an array:
In NumPy, changing the number of dimensions of an array is often necessary, especially when preparing data for certain computations or machine learning models. Two important functions for this are np.expand_dims() and np.squeeze().

- np.expand_dims()
  - Adds a new dimension (axis) to an array at a specified position.
  - Useful to increase the dimensionality of an array, for instance, converting a 1D array into a 2D array.

Syntax:
```
np.expand_dims(array, axis)
```
- axis: Position where the new dimension is added.

In [5]:
arr = np.array([1, 2, 3])
print("Original arrray:\n",arr)
print("Original shape", arr.shape, "\n")

# Here, we added a new dimension at axis 0 (the front).
# Now the array is 2D with 1 row and 3 columns.
expanded_arr = np.expand_dims(arr, axis = 0)
print("Expanded array:\n", expanded_arr)
print("Expanded array shape:", expanded_arr.shape, "\n")


# Here, we added a new dimension at axis 1 (the second axis).
# Now the array is 2D with 3 rows and 1 column.
expanded_arr2 = np.expand_dims(arr, axis = 1)
print("Expanded array:\n", expanded_arr2)
print("Expanded array shape:", expanded_arr2.shape)

Original arrray:
 [1 2 3]
Original shape (3,) 

Expanded array:
 [[1 2 3]]
Expanded array shape: (1, 3) 

Expanded array:
 [[1]
 [2]
 [3]]
Expanded array shape: (3, 1)


### np.squeeze()
- Removes all dimensions of size 1 from the shape of an array.
- Useful to reduce unnecessary dimensions (remove single-dimensional entries).

Syntax:
`np.squeeze(array, axis=None)`
- axis: Optional, specifies exact dimension(s) of size 1 to remove.

In [36]:
arr = np.array([[[1], [2], [3]]])
print("Original array:", arr)
print("Original array shape:", arr.shape, "\n")

squeezed_arr = np.squeeze(arr)
print("Squeezed array:\n", squeezed_arr, "\n")
print("Squeezed array shape:", squeezed_arr.shape)

# If you want to remove a specific axis only if it's of size 1:
arr2 = np.array([[[1], [2], [3]]])
squeezed = np.squeeze(arr2, axis=0)
print("Squeezed array:",squeezed.shape)

Original array: [[[1]
  [2]
  [3]]]
Original array shape: (1, 3, 1) 

Squeezed array:
 [1 2 3] 

Squeezed array shape: (3,)
Squeezed array: (3, 1)


### Splitting
Splitting arrays in NumPy lets you divide a large array into smaller subarrays. The functions np.split(), np.hsplit(), and np.vsplit() are commonly used for this purpose.

#### np.split()
- Divides an array into multiple subarrays along a specified axis.
- Syntax: `np.split(array, indices_or_sections, axis=0)`
  - `indices_or_sections`: Number of equal sections or list of index positions where splits will happen.
  - `axis`: 0 (rows by default), can be changed for different dimensions.

In [19]:
a = np.array([1, 2, 3, 4, 5, 6])
split_a = np.split(a, 3)
print("Splited array:", split_a)

# For 2-D arrays, specify axis = 1 to split columns
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_b = np.split(b, 3, axis=1)
print("Splited 2-d array:\n", split_b)

Splited array: [array([1, 2]), array([3, 4]), array([5, 6])]
Splited 2-d array:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


### np.hsplit()
- Shortcut for splitting an array horizontally (column-wise) into multiple subarrays.
- Only works on arrays with 2 or more dimensions.

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
new_arr = np.hsplit(arr_2d, 2)
print("Horizontal splid of 2-d array:\n", new_arr)

# Each subarray here gets two columns.

Horizontal splid of 2-d array:
 [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


### np.vsplit()
- Shortcut for splitting an array vertically (row-wise) into multiple subarrays.
- Only works on arrays with 2 or more dimensions.

In [24]:
new_v_arr = np.vsplit(arr_2d, 2)
print("Vertical split of 2-d array:\n", new_v_arr)

# Each subarray here gets one row

Vertical split of 2-d array:
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


### Tip: If the array cannot be split equally (without a remainder), NumPy will raise an error. You can provide custom indices for more flexibility with np.split().
- With np.split(), you can specify a list of indices to split the array at, which offers flexibility when the array cannot be divided into equal parts.

### How to Use Custom Indices with np.split()
- Instead of just giving a number of equal splits, provide a list of index positions where splits should occur.

In [28]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
splited_a = np.split(a, [3, 5])
print("Customly splited array:\n", splited_a)

''' 
- The array is split into three subarrays:
  - First: elements before index 3
  - Second: elements from index 3 up to (but not including) index 5
  - Third: elements from index 5 to end
'''

Customly splited array:
 [array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]


' \n- The array is split into three subarrays:\n  - First: elements before index 3\n  - Second: elements from index 3 up to (but not including) index 5\n  - Third: elements from index 5 to end\n'

### np.random()
- NumPy’s np.random module provides fast functions to generate random numbers and sample data, which is crucial for simulations, bootstrapping, data augmentation, and testing models.

### Generating Random Data
NumPy can quickly create arrays filled with random values from different distributions:

### Uniform Distribution
- Produces evenly spread numbers over a given interval.
- `np.random.uniform(low, high, size)`

In [38]:
uniform = np.random.uniform(0, 1, 5)
# 5 random numbers between 0 and 1
print("Uniform disrtibution example:", uniform)

Uniform disrtibution example: [0.54980651 0.59149286 0.95137765 0.90544148 0.34062681]


### Normal (Gaussian) Distribution
- Produces data centered around a mean with a specified standard deviation.
- `np.random.normal(loc, scale, size)`

In [42]:
normal = np.random.normal(0, 1, 5)
# mean = 0, standard deviation = 1, 5 random samples
print("Normal distribution example:", normal)
print("Mean", np.mean(normal))
print("Standard deviation:", np.std(normal))

Normal distribution example: [0.15060355 0.34933002 1.80403602 0.97139822 0.10256193]
Mean 0.6755859461730596
Standard deviation: 0.6436319489374495


### Binomial Distribution
- Used for binary outcomes, like flipping a coin or test results.
- np.random.binomial(n, p, size)

In [44]:
binomial = np.random.binomial(10, 0.5, 5)
print("Binomia distribution example:", binomial)

# 5 trials of 10 coin flips (success probability 0.5)

Binomia distribution example: [5 6 3 4 5]


### Sampling Random Integers
- `np.random.randint(low, high, size)`

In [46]:
rand_int = np.random.randint(1, 10, 5)
# 5 random integers from [1, 9]
print("Random integers example:", rand_int)

Random integers example: [2 1 8 7 2]


### linear algebra operations
- NumPy includes efficient linear algebra operations, which are essential for data analysis, scientific computing, and machine learning. Here’s a summary of the most important operations and how they work:

### Dot Product and Matrix Multiplication
- Dot Product: Computes the sum product of two arrays. For 1D, it’s the dot product; for 2D, it’s matrix multiplication.

In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot product of a and b:", dot_product)

Dot product of a and b: 32


### Matrix Multiplication: For 2D arrays (matrices), use @ operator or np.matmul():

In [58]:
A = np.array([[4, 5, 9], [3, 9, 8]])
B = np.array([[7, 8], [8, 2], [5, 3]])
prod = A @ B
print("Matrix multiplication of A and B:\n", prod)

Matrix multiplication of A and B:
 [[113  69]
 [133  66]]


### Matrix Inversion
- Calculates the inverse of a square matrix using np.linalg.inv():

In [59]:
M = np.array([[1, 2], [3, 4]])
inverse_of_M = np.linalg.inv(M)
print("Inverse of matrix M:\n", inverse_of_M)

Inverse of matrix M:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Determinant
- Computes determinant using np.linalg.det(), important for understanding matrix properties:

In [60]:
det_M = np.linalg.det(M)
print("Determinant of the matrix M:", det_M)

Determinant of the matrix M: -2.0000000000000004


### Cross product

In [62]:
x = np.array([[2, 3, 4], [4, 5, 6]])
y = np.array([[7, 8, 9], [3, 2, 1]])
cross_product = np.cross(x, y)
print("Cross product of x and y:\n", cross_product)

Cross product of x and y:
 [[-5 10 -5]
 [-7 14 -7]]


### Handling missing or invalid data
- Handling missing or invalid data is crucial in real-world datasets, and NumPy provides tools to work with NaN (Not a Number) values efficiently.

### Identifying NaN Values
Use `np.isnan(array)` to create a Boolean mask showing where NaNs appear.

In [64]:
arr = np.array([1, np.nan, 3, np.nan])
mask = np.isnan(arr)
print(mask)

[False  True False  True]


### Replacing NaN Values
- Use np.nan_to_num(array) to replace NaN with zero (or other specified values).

In [68]:
arr_fixed = np.nan_to_num(arr)
print(arr_fixed)

# We can set custom replacements with its arguments.
arr_custom = np.nan_to_num(arr, nan = 99)
print(arr_custom)

[1. 0. 3. 0.]
[ 1. 99.  3. 99.]


### Ignoring NaN in Calculations
- Many NumPy functions have a nan* version (e.g., np.nanmean(), np.nansum()) that ignore NaN when computing results.

In [69]:
mean = np.nanmean(arr)
print(mean)

2.0


### Why Manage NaN?
- NaNs can cause calculations to fail or produce misleading results.
- Identifying, replacing, or ignoring NaNs is essential for cleaning data, statistical analysis, or applying models.

These methods help ensure that missing or invalid data does not disrupt analysis or lead to errors in downstream computations.NumPy offers simple and powerful ways to handle missing or invalid data, typically represented as NaN (Not a Number).

- Use `np.isnan(array)` to get a Boolean array where True indicates an invalid (NaN) value.
- Use `np.any()` to check if any element in this Boolean array is True.
- Bonus: Check for Infinities too
  - Use `np.isinf(array)` to detect infinite values.
  - Combine both to check for either NaN or infinite values:

In [71]:
arr = np.array([1, 2, np.nan, 4, 5])

has_invalid = np.any(np.isnan(arr) | np.isinf(arr))
print(has_invalid)

True
