# Sample Finance Data (Annual Profit/Loss)
- Columns: [company_id, 2020, 2021, 2022, 2023, 2024]
- Rows: Each row is one company’s yearly profit/loss (can include negative values to indicate losses).

In [2]:
import numpy as np

In [4]:
finance_data = np.array([
    [1, 50000, 75000, -12000, 20000, 65000],   # Company A
    [2, 120000, -60000, 95000, 102000, 90000], # Company B
    [3, -20000, 40000, 45000, 70000, 75000],   # Company C
    [4, 260000, 310000, 290000, 280000, 265000],  # Company D
    [5, 150000, 152000, 155000, 155000, 160000],  # Company E
    [6, 80000, 120000, 115000, 117000, 119000]    # Company F
])

In [18]:
company_id = finance_data[:, 0]
values = finance_data[:, 1:]

In [19]:
# 1. Total profit/lose for each company across years
total_profit = np.sum(values, axis = 1)
print("Total profit/loss per company:\n", total_profit)

Total profit/loss per company:
 [ 198000  347000  210000 1405000  772000  551000]


In [20]:
# 2. Year-over-year changes (differences) and growth rates

yearly_change = np.diff(values, axis = 1)
growth_rate = yearly_change / values[:, :-1] * 100

print("Year over year changes:\n", yearly_change, "\n")
print("Year over year growth rate (%)\n", growth_rate)

Year over year changes:
 [[  25000  -87000   32000   45000]
 [-180000  155000    7000  -12000]
 [  60000    5000   25000    5000]
 [  50000  -20000  -10000  -15000]
 [   2000    3000       0    5000]
 [  40000   -5000    2000    2000]] 

Year over year growth rate (%)
 [[  50.         -116.         -266.66666667  225.        ]
 [-150.         -258.33333333    7.36842105  -11.76470588]
 [-300.           12.5          55.55555556    7.14285714]
 [  19.23076923   -6.4516129    -3.44827586   -5.35714286]
 [   1.33333333    1.97368421    0.            3.22580645]
 [  50.           -4.16666667    1.73913043    1.70940171]]


In [21]:
# 3. Identify companis with losses (negative numbers) any year
loss_mask = np.any(values < 0, axis = 1)
companies_losses = company_id[loss_mask]

print("Company with losses in any year:\n", companies_losses)

Company with losses in any year:
 [1 2 3]


In [23]:
# 4. Rank companies by overall performance (total profit descending)
rank_indices = np.argsort(total_profit)[::-1]
rank_companies = company_id[rank_indices]
rank_total = total_profit[rank_indices]

print("Ranked companies by total profit:\n", rank_companies)
print("Corresponding total profit:\n", rank_total)

Ranked companies by total profit:
 [4 5 6 2 3 1]
Corresponding total profit:
 [1405000  772000  551000  347000  210000  198000]


In [24]:
# 5. Detect volatility (std deviation of profits across years)
volatility = np.std(values, axis = 1)
print("Volatility (standard deviation) per company:\n", volatility)

Volatility (standard deviation) per company:
 [31790.56463796 65493.81650202 33852.62175962 18000.
  3382.30690506 15197.36819321]


In [25]:
# 6. Mask/filter companies with losses in two or more years
loss_counts = np.sum(values < 0, axis = 1)
mask_two_or_more_losses = loss_counts >= 2
companies_with_multiple_losses = company_id[mask_two_or_more_losses]
print("Companies with two or more losses:\n", companies_with_multiple_losses)

Companies with two or more losses:
 []


In [29]:
# 7. Forecast next year (2025) profit using simple linear extrapolation
# Using difference between last two years to estimate next year
last_year_diff = values[:, -1] - values[:, -2]
forecast_2025 = values[:, -1] + last_year_diff
print("Forecasted 2025 profit:\n", forecast_2025)

Forecasted 2025 profit:
 [110000  78000  80000 250000 165000 121000]


In [32]:
# 8. Visualize trends (profit turning to loss or vice versa)
# Find year pairs where sign changes between consecutive years
sign_changes = np.diff(np.sign(values), axis = 1) != 0
companies_sign_change = company_id[np.any(sign_changes, axis = 1)]
print("Companies with profit/loss sign change:\n", companies_sign_change)

Companies with profit/loss sign change:
 [1 2 3]
