# Weather Data (Daily Temperatures in °C)
- Each row represents a city.
- Each column is temperature for one day (e.g., 7 days for a week).

In [2]:
import numpy as np

In [3]:
weather_data = np.array([
    [25, 27, 26, 28, 29, 30, 31],  # City A
    [15, 17, 18, 20, 19, 16, 15],  # City B
    [5,  7,  6,  5,  4,  3,  2],   # City C
    [22, 21, 23, 24, 25, 25, 26]   # City D
])

In [9]:
# 1. Daily average temperature of each city
average_temp = np.mean(weather_data, axis = 1)
print("Average temperature of each city:\n", average_temp)

Average temperature of each city:
 [28.         17.14285714  4.57142857 23.71428571]


In [10]:
# 2. Average temperature across cities for each day
daily_avg = np.mean(weather_data, axis = 0)
print("Daily average temperature across cities for each day:\n", daily_avg)

Daily average temperature across cities for each day:
 [16.75 18.   18.25 19.25 19.25 18.5  18.5 ]


In [11]:
# 3. Temperature range per city
temp_range = np.ptp(weather_data, axis = 1)
print("Temperature range per city:\n", temp_range)

Temperature range per city:
 [6 5 5 5]


In [12]:
# 4. Temperature volatility per city
temp_volatility = np.std(weather_data, axis = 1)
print("Temperature Volatility per city:\n", temp_volatility)

Temperature Volatility per city:
 [2.         1.80701581 1.59078982 1.66598626]


In [15]:
# 5. Days with extreme temperature across the cities (max and min temp days)
max_temp_days = np.argmax(weather_data, axis=0)
min_temp_days = np.argmin(weather_data, axis=0)
print("City index with max temperature each day:\n", max_temp_days)
print("City index with min temperature each day:\n", min_temp_days)

City index with max temperature each day:
 [0 0 0 0 0 0 0]
City index with min temperature each day:
 [2 2 2 2 2 2 2]


In [ ]:
# 6. Detect trends: rising or falling temperatures (Boolean mask per city)
temp_diff = np.diff(weather_data, axis = 1)
rising_temp = temp_diff > 0
falling_temp = temp_diff < 0
print("Rising temperature mask:\n", rising_temp)
print("Falling temperature mask:\n", falling_temp)

Rising temperature mask:
 [[ True False  True  True  True  True]
 [ True  True  True False False False]
 [ True False False False False False]
 [False  True  True  True False  True]]
Falling temperature mask:
 [[False  True False False False False]
 [False False False  True  True  True]
 [False  True  True  True  True  True]
 [ True False False False False False]]


In [17]:
# 7. Filter cities with highest weekly average
high_weekly_avg = np.argmax(average_temp)
print("Cities with highest weekly average temperature:\n", high_weekly_avg + 1)

Cities with highest weekly average temperature:
 1


In [18]:
# 8. Compare temperature profiles between two cities (City A and City D)
city_a = weather_data[0, :]
city_d = weather_data[3, :]
print("City A temperature:\n", city_a)
print("City D temperature:\n", city_d)

City A temperature:
 [25 27 26 28 29 30 31]
City D temperature:
 [22 21 23 24 25 25 26]


In [22]:
# 9. Calculate moving averages to smooth daily fluctuations (window size 3)
def moving_average(arr, window = 3):
  return np.convolve(arr, np.ones(window)/window, mode='valid')

smoothed_city_a = moving_average(city_a)
print("Smoothed City A temperatures (3-day moving average):", smoothed_city_a)

Smoothed City A temperatures (3-day moving average): [26.         27.         27.66666667 29.         30.        ]


## What is a Moving Average?
- A moving average smooths out short-term fluctuations by replacing each point with the average of its neighbors (defined by a window size).

- `np.ones(window)` → creates an array of all 1’s, length = `window`.
  - ```
    np.ones(3) = [1, 1, 1]
    ```
- `np.ones(window) / window` → normalizes so it becomes an averaging filter.
  - ```
    [1, 1, 1] / 3 = [1/3, 1/3, 1/3]
    ```

- `np.convolve(arr, filter, mode='valid')` → slides this filter across the array, multiplying and summing at each step.
  - `'valid'` → only positions where the filter fully overlaps with arr.